[versions]
junit-jupiter = "5.13.4"
lombok = "1.18.42"
assertJ= "3.27.6"
mockito= "4.11.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito"}